# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ICSOB 2022
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
The International Conference on Software Business (ICSOB) attracts both researchers and practitioners who are concerned with software-intensive business in different ways, and brings them together to share their findings and experiences from the field of software-intensive business.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://icsob2022.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username: jekyll

# Build settings
markdown: kramdown
#theme: minima
remote_theme: "melegati/jekyll-theme-conference"
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-target-blank

target-blank:
  css_class: ext-link

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#comment

sass:
  style: compressed

# Additional exclude from processing
exclude:
  - .github/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - purgecss.config.js

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room

conference:
  # Language
  lang: en

  # Show theme errors:
  show_errors: True

  # Navigation bar
  navigation:
    logo:
      img: "logo.png"
      url: "https://icsob2022.github.io/"
    links:
      - name: Home
        relative_url: /
      - name: Call for Submissions
        menu:
          - name: Call for Research Papers
            relative_url: "/#CallForResearchPapers"
          - name: EasyChair Paper Submission
            relative_url: "/#EasyChairPaperSubmission"
          - name: Important Dates
            relative_url: "/#ImportantDates"
          - name: Submission Formats
            relative_url: "/#SubmissionFormats"
          - name: Other calls for submission
            relative_url: "/#OtherCallsForSubmission"

      - name: Important Dates
        relative_url: /importantdates/
      - name: Organisation
        relative_url: /organisation/
      - name: Venue
        relative_url: /venue/
      - name: Travel information
        relative_url: /location/
      - name: Series
        menu:
          - name: 2022 (current)
            disabled: true
          - name: 2021
            relative_url: "https://icsob2021.org/"
          - name: 2020
            relative_url: "https://icsob.wordpress.com/"
          - name: 2019
            relative_url: "https://icsob2019.wordpress.com/"

  # Link Preview for Sharing
  link_preview:
    # also adapt "preposition" property at top for more meaningful descriptions
    disable: false
    img:
      twitter: "twitter_preview.png" # inside /assets/images/
      open_graph: "facebook_preview.png" # inside /assets/images/

  # Main landing page
  main:
    #logo:
    # img: 'bozen1.png'
    links:
      - name: Program
        relative_url: /program/
      - name: How to get there
        relative_url: /location/
      - name: Tickets
        disabled: true
        absolute_url: ""

  # Information boxes
  info_bars:
    - title: Welcome to the Conference Theme for Jekyll!
      color: primary
      main_only: true
      text: |
        The Theme was originally made for the [Winterkongress](https://www.digitale-gesellschaft.ch/kongress/), a yearly conference of the [Digital Society Switzerland](https://digitale-gesellschaft.ch/).

        ---

        See the [README](github.com/DigitaleGesellschaft/jekyll-theme-conference/) on the project's GitHub repository for further information on how to configure and adapt it to your needs.

      pages_only: true

  # Live indications
  live:
    date: 01.01.2020
    timezone: GMT+1
    stop: 240 # in minutes
    streaming:
      enable: true
      pause: 60 # in minutes
      prepend: 5 # in minutes
      extend: 5 # in minutes
    demo:
      enable: false
      duration: 300 # in seconds
      pause: 10 # in seconds

  map:
    # Initial map center point
    home_coord: 47.37808, 48.53935
    # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
    # The following do match the Bootstrap design not too badly:
    #   - Hydda.Full
    #   - Thunderforest.Neighbourhood
    #   - Esri.WorldTopoMap
    map_provider: "OpenStreetMap.Mapnik"
    default_zoom: 17

  talks:
    # Talk categories
    main_categories:
      - name: Cat A
        color: info
      - name: Cat B
        color: success

    # Hide icons on talk overview page
    hide_icons: false

  speakers:
    # Show first and last name
    show_firstname: true

  location:
    # Disable links to locations
    hide: false
    # URL of location / room overview page
    url: "/location"
    # Main page title shown on location/room navigation bar
    navbar_title: "Location"
    # Show map on location main page
    map: true

  program:
    # URL of program page
    url: "/program"

    # Time steps in program table
    time_steps: 15 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: true
